### PR TITLE
ease of use improvements

### PR DESCRIPTION
**Pull request by rlKoekie**
I've made some improvements to the script that should make it easier to use. 
Input is now parsed using argparse, I've added an option for testing the connection with the Kamstrup, and an option for testing the connection to Domoticz, and some sanity checks during startup.

### CODE REVIEW

**Comment by ronaldvdmeer** [comment]
Nice one! Thank you very much! Have you tested it with exactly the same hardware as mentioned in the README.md?

**Comment by rlKoekie** [comment]
I tested with a USB IR probe on a Kamstrup Multical 402. I forgot to check the model number on the IR probe, but it worked out of the box without modifying any of the code related to transmitting/receiving data.

**Comment by ronaldvdmeer** [comment]
I see. I’m not able to test it myself currently so I need some confirmation it works with the IR Optical Probe IEC1107 IEC61107 before I can merge this PR. Are you able to verify it somehow?

**Comment by rlKoekie** [comment]
I've asked my friend for the details on the IR probe. This is the model we used: https://shop.weidmann-elektronik.de/index.php?page=product&info=24
The specs are:
```
USB Infrarot Schreib/Lesekopf zum Auslesen von elektronischen Stromzähler.
Kompatibel mit allen elektronischen Stromzähler, welche eine D0 Infrarot Info-Schnittstelle besitzen und Daten im SML oder ASCIIFormat ausgeben.
Kompatibel mit Softwareprogrammen wie z.B. "Volkszähler" und Co.

Unter Linux wird das Gerät automatisch erkannt und ist unter /dev/ttyUSB0 erreichbar.

Technische Daten
Funktion: Infrarot Sendediode (Tx), Infrarot Phototransistor (Rx)
IC: FTDI FT232R / FT230X USB-to-UART Serial Converter
Typ: USB 2.0
RoHS: konform
Kabellänge: 3m
Maße: ⌀xH (mm): 32x19
Unterstützte Baudraten: 300 Baud bis 28800 Baud
UART interface support für 7 oder 8 data bits, 1 oder 2 stop bits und odd / even / mark / space / no parity
Unterstützte Normen: DIN EN 62056-21, IEC-62056-21

Integrierter Magnet für eine klebefreie Montage.
```

It behaves the same as IEC1107 IEC61107 I believe, but I'm not that well versed in IR Optical Probes :smile:

**Comment by ronaldvdmeer** [comment]
Me neither :) Could you update this PR when your friend replied?

**Comment by rlKoekie** [comment]
Just did. He told me 1107 and 62056-21 are basically the same protocol. 1107 is the old name, 62056-21 the new. Wikipedia seems to confirm this: 
https://en.wikipedia.org/wiki/IEC_62056#IEC_62056-21

Small sidenote that I should maybe have mentioned more clearly in the pull request: the new input is slightly different from the old input, so the script is not drop-in-place compatible with the previous version. Changing old input to the new input is pretty trivial though

**Pull request merged**
